databases:
  - name: devjobs
    databaseName: devjobs
    user: devjobs
    plan: free

services:
  - type: web
    plan: free
    name: devjobs
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn devjobs.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: devjobs
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4