# Generated by Django 5.0.1 on 2024-01-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='country',
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
